# Generated by Django 5.2.1 on 2026-09-26 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="recipient_coach",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_contact_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
