# Generated by Django 5.2.1 on 2026-06-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('language', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], max_length=2)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('slug', 'language')},
            },
        ),
    ]
